version: "3.8"

services:
 db:
   image: postgis/postgis:15-3.3
   container_name: firms_db
   restart: always
   ports:
     - "5433:5432"
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   volumes:
     - pgdata:/var/lib/postgresql/data
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
     interval: 5s
     timeout: 5s
     retries: 5

 api:
   build:
     context: .
     dockerfile: api/Dockerfile
   container_name: firms_api
   ports:
     - "8001:8000"
   environment:
     - POSTGRES_HOST=db
   depends_on:
     db:
       condition: service_healthy
   volumes:
     - ./api:/app/api  # Esto monta la carpeta api en el contenedor
   env_file:
     - .env

 etl:
   build:
     context: .
     dockerfile: etl/Dockerfile
   container_name: firms_etl
   environment:
     - POSTGRES_HOST=db
     - TZ=Etc/UTC
   depends_on:
     db:
       condition: service_healthy
   env_file:
     - .env

 web:
   image: nginx:alpine
   container_name: firms_web
   volumes:
     - ./web:/usr/share/nginx/html
     - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
   ports:
     - "8080:80"
   depends_on:
     - api

volumes:
 pgdata: